### ISSUE TITLE
Error: Use of const in strict mode

### ISSUE THREAD

**Issue by jadbox** [doapp-ryanp/dynamodb-local#1]
const JARNAME = 'DynamoDBLocal.jar';
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/jdunlap/github/vidroll/vidroll-portal/gulpfile.js:9:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

OS: Debian Jessie
node --version v0.10.38

**Comment by doapp-ryanp** [comment]
Thats because the `const` keyword was introduced in ES6.  Your version of node does not support ES6 constants.  I developed this module with some ES6 support required (const, let, Promise).  I'll update the docs. https://iojs.org/en/es6.html
